baseURL = "https://nihars.com/"
languageCode = "en-us"
title = "Nihar Samantaray"
theme = "hugo-ink"

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
subtitle = "Linux Enthusiast who [build](/project) in internet."

    # Content types which are included in home page recent posts list.
mainSections = ["posts","note","project"]

    # Content types which are excludes Disqus comments.
disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "https://niharokz.gitlab.io/nihars.com/icons/favicon.ico"
    avatar = "https://niharokz.gitlab.io/nihars.com/icons/logo.png"
    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
mode = "dark" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
#customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
#customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
#customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]

# Main menu which appears below site header.
[[menu.main]]
name = "HOME"
url = "/"
weight = 1

[[menu.main]]
name = "PROJECT"
url = "/project"
weight = 2

[[menu.main]]
name = "NOTE"
url = "/note"
weight = 3

[[menu.main]]
name = "TAGS"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/niharokz"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:mail@nihars.com"



# Enable tags.
[taxonomies]
   tag = "tags"
