url : "https://nihars.com"
title : "Nihar Samantaray"
subtitle : "Linux enthusiast who build in internet"
description : "Personal webpage of another Systems engineer who is interested on Open Source projects based for linux environments"
css : "resource/css/main.css"
js : "resource/js/dark_mode.js"
favicon : "resource/image/favicon.ico"
avatar : "resource/image/nihar.jpeg"
no_of_post_per_page : 8
home_about : "content/extra/home.md"

header :
 - 
  name : "note"
  url : "/note"
  type : "list"
 -        
  name : "project"
  url : "/project"
  type : "list"
 -
  name : "unrelated"
  url : "/unrelated"
  type : "list"
 -
  name : "Contact"
  url : "/contact"
  type : "singlepage"
  file : "content/extra/contact.md"

footer :
 -
  name : "Home"
  url : "/"
  type : "link"
 -
  name : "RSS"
  url : "/rss.xml"
  type : "link"
 -
  name : "Resume"
  url : "/resume"
  type : "singlepage"
  file : "content/extra/resume.md"
 -
  name : "Gitlab"
  url : "https://gitlab.com/niharokz"
  type : "link"
 -
  name : "Search"
  url : "/search"
  type : "singlepage"
  file : "content/extra/search.md"
 -
  name : "LinkedIn"
  url : "https://www.linkedin.com/in/niharsamantaray/"
  type : "link"
 
